version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  aircraft.tasks.api:
    image: ${DOCKER_REGISTRY-}aircrafttasks
    build:
      context: .
      dockerfile: Aircraft.Tasks.Api/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - rabbitmq